# ===== FACULTY KNOWLEDGE BASE =====
# Centralized data structure for all faculty information
# This file should be updated when faculty changes occur

# Primary faculty database - maps various name formats to standardized names
KNOWN_FACULTY = {
    # ===== CURRENT FACULTY =====
    # Immunity & Infection Department
    "debasisa mohanty": "Dr. Debasisa Mohanty",
    "agam singh": "Dr. Agam P. Singh",
    "agam p singh": "Dr. Agam P. Singh",
    "agam p. singh": "Dr. Agam P. Singh",
    "dr agam p. singh": "Dr. Agam P. Singh",
    "devinder sehgal": "Dr. Devinder Sehgal",
    "nimesh gupta": "Dr. Nimesh Gupta",
    "prafullakumar tailor": "Dr. Prafullakumar B. Tailor",
    "prafullakumar b tailor": "Dr. Prafullakumar B. Tailor",
    "santiswarup singha": "Dr. Santiswarup Singha",
    "soumen basak": "Dr. Soumen Basak",
    "tanmay majumdar": "Dr. Tanmay Majumdar",
    "veena s patil": "Dr. Veena S. Patil",
    # Genetics, Cell Signalling & Cancer Biology
    "aneeshkumar a.g": "Dr. Aneeshkumar A.G.",
    "anil kumar": "Dr. Anil Kumar",
    "arnab mukhopadhyay": "Dr. Arnab Mukhopadhyay",
    "devram ghorpade": "Dr. Devram Ghorpade",
    "madhulika srivastava": "Dr. Madhulika Srivastava",
    "pushkar sharma": "Dr. Pushkar Sharma",
    "sagar sengupta": "Dr. Sagar Sengupta",
    "sanjeev das": "Dr. Sanjeev Das",
    "rajesh kumar yadav": "Dr. Rajesh Kumar Yadav",
    "rkyadav": "Dr. Rajesh Kumar Yadav",
    "vinay nandicoori": "Dr. Vinay K. Nandicoori",
    "vinay k nandicoori": "Dr. Vinay K. Nandicoori",
    # Chemical Biology, Biochemistry & Structural Biology
    "apurba kumar sau": "Dr. Apurba Kumar Sau",
    "bichitra biswal": "Dr. Bichitra K. Biswal",
    "bichitra k biswal": "Dr. Bichitra K. Biswal",
    "dr bichitra k biswal": "Dr. Bichitra K. Biswal",
    "debasisa mohanty": "Dr. Debasisa Mohanty",
    "mohanty": "Dr. Debasisa Mohanty",
    "g senthil kumar": "Dr. G. Senthil Kumar",
    "monica sundd": "Dr. Monica Sundd",
    "s gopalan sampathkumar": "Dr. S. Gopalan Sampathkumar",
    "sarika gupta": "Dr. Sarika Gupta",
    "chhuttan lal meena": "Dr. Chhuttan Lal Meena",
    "narendra kumar": "Dr. Narendra Kumar",
    "p nagarajan": "Dr. P. Nagarajan",
    "ankita varshney": "Dr. Ankita Varshney",
    "mohanty": "Dr. Debasisa Mohanty",
    # Former Faculty
    # Immunity & Infection
    "g.p. talwar": "Prof. G.P. Talwar",
    "gp talwar": "Prof. G.P. Talwar",
    "rama mukherjee": "Rama Mukherjee",
    "s.e. hasnain": "S.E. Hasnain",
    "sudhanshu vrati": "Sudhanshu Vrati",
    "sangeeta bhaskar": "Dr. Sangeeta Bhaskar",
    "amulya panda": "Dr. Amulya K. Panda",
    "amulya k panda": "Dr. Amulya K. Panda",
    "anna george": "Dr. Anna George",
    "akhil c banerjea": "Dr. Akhil C. Banerjea",
    "mohd ayub qadri": "Dr. Mohd. Ayub Qadri",
    "pramod k upadhyay": "Dr. Pramod K. Upadhyay",
    "rahul pal": "Dr. Rahul Pal",
    "satyajit rath": "Dr. Satyajit Rath",
    "vineeta bal": "Dr. Vineeta Bal",
    # Genetics, Cell Signalling & Cancer Biology
    "rajesh k anand": "Rajesh K. Anand",
    "ramesh juyal": "Ramesh Juyal",
    "sandeep saxena": "Dr. Sandeep Saxena",
    "anil k suri": "Dr. Anil K. Suri",
    "rajni rani": "Dr. Rajni Rani",
    "sher ali": "Dr. Sher Ali",
    "vijay k yadav": "Dr. Vijay K. Yadav",
    # Chemical Biology, Biochemistry & Structural Biology
    "ram vishwakarma": "Ram Vishwakarma",
    "dinakar salunke": "Dinakar M. Salunke",
    "dinakar m salunke": "Dinakar M. Salunke",
    "avadesha surolia": "Prof. Avadesha Surolia",
    "rajendra p roy": "Dr. Rajendra P. Roy",
    "rajesh s gokhale": "Dr. Rajesh S. Gokhale",
    "vidya raghunathan": "Dr. Vidya Raghunathan",
    "janendra batra": "Dr. Janendra K. Batra",
    "janendra k batra": "Dr. Janendra K. Batra",
    "lalit c garg": "Dr. Lalit C. Garg",
    "kanwaljeet kaur": "Dr. Kanwaljeet Kaur",
    # Reproduction, Development & Cell Biology
    "shakti n upadhyay": "Shakti N. Upadhyay",
    "satish m totey": "Satish M. Totey",
    "ravi dhar": "Ravi Dhar",
    "sandip k basu": "Sandip K. Basu",
    "om singh": "Om Singh",
    "asok mukhopadhyay": "Dr. Asok Mukhopadhyay",
    "chandrima shaha": "Dr. Chandrima Shaha",
    "satish k gupta": "Dr. Satish K. Gupta",
    "amitabha mukhopadhyay": "Dr. Amitabha Mukhopadhyay",
    "subeer s majumdar": "Dr. Subeer S. Majumdar",
}

# Disambiguation strategies for ambiguous surnames/names
AMBIGUOUS_NAMES = {
    "gupta": ["Dr. Sarika Gupta", "Dr. Nimesh Gupta"],
    "kumar": ["Dr. Anil Kumar", "Dr. Rajesh Kumar Yadav", "Dr. Narendra Kumar"],
    # Add more ambiguous mappings as faculty grows
}

# First name to full name mapping for casual/informal queries
FIRST_NAMES = {
    # Current Faculty — Immunity & Infection
    "agam": "Dr. Agam P. Singh",
    "devinder": "Dr. Devinder Sehgal",
    "nimesh": "Dr. Nimesh Gupta",
    "prafullakumar": "Dr. Prafullakumar B. Tailor",
    "santiswarup": "Dr. Santiswarup Singha",
    "soumen": "Dr. Soumen Basak",
    "tanmay": "Dr. Tanmay Majumdar",
    "veena": "Dr. Veena S. Patil",
    # Current Faculty — Genetics, Cell Signalling & Cancer Biology
    "aneeshkumar": "Dr. Aneeshkumar A.G.",
    "anil": "Dr. Anil Kumar",
    "arnab": "Dr. Arnab Mukhopadhyay",
    "devram": "Dr. Devram Ghorpade",
    "madhulika": "Dr. Madhulika Srivastava",
    "pushkar": "Dr. Pushkar Sharma",
    "sagar": "Dr. Sagar Sengupta",
    "sanjeev": "Dr. Sanjeev Das",
    "rajesh": "Dr. Rajesh Kumar Yadav",
    "vinay": "Dr. Vinay K. Nandicoori",
    # Current Faculty — Chemical Biology, Biochemistry & Structural Biology
    "apurba": "Dr. Apurba Kumar Sau",
    "bichitra": "Dr. Bichitra K. Biswal",
    "debasisa": "Dr. Debasisa Mohanty",
    "senthil": "Dr. G. Senthil Kumar",
    "monica": "Dr. Monica Sundd",
    "monica sudd": "Dr. Monica Sundd",
    "dr. monica sundd": "Dr. Monica Sundd",
    "professor monica sundd": "Dr. Monica Sundd",
    "prof monica sundd": "Dr. Monica Sundd",
    "gopalan": "Dr. S. Gopalan Sampathkumar",
    "sarika": "Dr. Sarika Gupta",
    "chhuttan": "Dr. Chhuttan Lal Meena",
    "narendra": "Dr. Narendra Kumar",
    "narender": "Dr. Narendra Kumar",
    "nagarajan": "Dr. P. Nagarajan",
    "ankita": "Dr. Ankita Varshney",
    # Former Faculty — Immunity & Infection
    "gp": "Prof. G.P. Talwar",
    "rama": "Rama Mukherjee",
    "hasnain": "S.E. Hasnain",
    "sudhanshu": "Sudhanshu Vrati",
    "sangeeta": "Dr. Sangeeta Bhaskar",
    "amulya": "Dr. Amulya K. Panda",
    "anna": "Dr. Anna George",
    "akhil": "Dr. Akhil C. Banerjea",
    "ayub": "Dr. Mohd. Ayub Qadri",
    "pramod": "Dr. Pramod K. Upadhyay",
    "rahul": "Dr. Rahul Pal",
    "satyajit": "Dr. Satyajit Rath",
    "vineeta": "Dr. Vineeta Bal",
    # Former Faculty — Genetics, Cell Signalling & Cancer Biology
    "rajesh k": "Rajesh K. Anand",
    "ramesh": "Ramesh Juyal",
    "sandeep": "Dr. Sandeep Saxena",
    "anil k": "Dr. Anil K. Suri",
    "rajni": "Dr. Rajni Rani",
    "sher": "Dr. Sher Ali",
    "vijay": "Dr. Vijay K. Yadav",
    # Former Faculty — Chemical Biology, Biochemistry & Structural Biology
    "ram": "Ram Vishwakarma",
    "dinakar": "Dinakar M. Salunke",
    "avadesha": "Prof. Avadesha Surolia",
    "rajendra": "Dr. Rajendra P. Roy",
    "gokhale": "Dr. Rajesh S. Gokhale",
    "vidya": "Dr. Vidya Raghunathan",
    "janendra": "Dr. Janendra K. Batra",
    "lalit": "Dr. Lalit C. Garg",
    "kanwaljeet": "Dr. Kanwaljeet Kaur",
    # Former Faculty — Reproduction, Development & Cell Biology
    "shakti": "Shakti N. Upadhyay",
    "satish m": "Satish M. Totey",
    "ravi": "Ravi Dhar",
    "sandip": "Sandip K. Basu",
    "om": "Om Singh",
    "asok": "Dr. Asok Mukhopadhyay",
    "chandrima": "Dr. Chandrima Shaha",
    "satish": "Dr. Satish K. Gupta",
    "amitabha": "Dr. Amitabha Mukhopadhyay",
    "subeer": "Dr. Subeer S. Majumdar",
}

# Special position mappings for institutional queries
SPECIAL_POSITIONS = {
    "director": "Dr. Debasisa Mohanty",
    "current director": "Dr. Debasisa Mohanty",
    "nii director": "Dr. Debasisa Mohanty",
    "institute director": "Dr. Debasisa Mohanty",
}

# Department categorization for organizational queries
DEPARTMENT_FACULTY = {
    "immunity_infection": [
        "Dr. Agam P. Singh",
        "Dr. Devinder Sehgal",
        "Dr. Nimesh Gupta",
        "Dr. Prafullakumar B. Tailor",
        "Dr. Santiswarup Singha",
        "Dr. Soumen Basak",
        "Dr. Tanmay Majumdar",
        "Dr. Veena S. Patil",
    ],
    "genetics_cell_signalling": [
        "Dr. Aneeshkumar A.G.",
        "Dr. Anil Kumar",
        "Dr. Arnab Mukhopadhyay",
        "Dr. Devram Ghorpade",
        "Dr. Madhulika Srivastava",
        "Dr. Pushkar Sharma",
        "Dr. Sagar Sengupta",
        "Dr. Sanjeev Das",
        "Dr. Rajesh Kumar Yadav",
        "Dr. Vinay K. Nandicoori",
    ],
    "chemical_biology": [
        "Dr. Debasisa Mohanty",
        "Dr. Apurba Kumar Sau",
        "Dr. Bichitra K. Biswal",
        "Dr. G. Senthil Kumar",
        "Dr. Monica Sundd",
        "Dr. S. Gopalan Sampathkumar",
        "Dr. Sarika Gupta",
        "Dr. Chhuttan Lal Meena",
        "Dr. Narendra Kumar",
        "Dr. P. Nagarajan",
        "Dr. Ankita Varshney",
    ],
}

# Common false positives that should not be treated as names
FALSE_POSITIVES = {
    # Administrative terms
    "technical staff",
    "contact information",
    "research work",
    "faculty list",
    "current faculty",
    "alumni list",
    "staff members",
    "team members",
    "lab members",
    "phone extension",
    "email address",
    "about his",
    "about her",
    # Query artifacts
    "tell me",
    "show me",
    "give me",
    "list of",
    "all faculty",
    "nii faculty",
    "institute faculty",
    "working on",
    "research focus",
    "publications on",
    "interests and",
    "methods and",
    "contact details",
    "directory information",
    # Technical terms
    "computational biology",
    "structural biology",
    "molecular biology",
    "cell biology",
    "cancer biology",
    "research areas",
    "focus areas",
    # Process terms
    "recent publications",
    "latest papers",
    "current research",
    "research interests",
    "team members",
    "lab alumni",
    "faculty working",
    "staff working",
    "staff",
    "faculty",
    "list",
    "information",
    "contact",
    "details",
    "members",
    "working",
    "research",
    "publications",
    "interests",
    "methods",
    "focus",
    "areas",
    "technical",
    "administrative",
    "extension",
    "email",
    "phone",
    "directory",
    "current",
    "recent",
    "latest",
    "about",
    "tell",
    "show",
    "give",
}
